version: '3'
services:
  messaging-golang:
    image: iot-for-tillgenglighet/messaging-golang:latest
    build:
      context: ..
      dockerfile: ./deployments/Dockerfile
    restart: always
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      RABBITMQ_HOST: 'rabbitmq'
      RABBITMQ_USER: 'user'
      RABBITMQ_PASS: 'bitnami'
  
  rabbitmq:
    image: 'bitnami/rabbitmq:3.8'
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    volumes:
      - 'rabbitmq_data:/bitnami'

volumes:
  rabbitmq_data:
    driver: local
